#%RAML 1.0 DataType

type: object
properties:
  _id: 
    required: false
    type: number
  name: 
    required: true
    type: string
  date_of_released:
    required: true
    type: datetime
  rating:
    required: true
    type: number
  best_rating:
    required: true
    type: number
  